export const UPDATE_SHITFTS = "UPDATE_SHIFTS";

// export const ADD_TO_CART = "ADD_TO_CART";
// export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const CLEAR_CART = "CLEAR_CART";
// export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
// export const TOGGLE_CART = "TOGGLE_CART";

// export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
// export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";


export const UPDATE_SHIFTS = "UPDATE_SHIFTS";
export const ADD_TO_CALENDAR = "ADD_TO_CALENDAR";
export const ADD_MULTIPLE_TO_CALENDAR = "ADD_MULTIPLE_TO_CALENDAR";
export const REMOVE_FROM_CALENDAR = "REMOVE_FROM_CALENDAR";
export const CLEAR_CALENDAR = "CLEAR_CALENDAR";
export const UPDATE_CALENDAR_QUANTITY = "UPDATE_CALENDAR_QUANTITY";
export const TOGGLE_CALENDAR = "TOGGLE_CALENDAR";
export const UPDATE_HOSPITALS = "UPDATE_HOSPITALS";
export const UPDATE_CURRENT_HOSPITAL = "UPDATE_CURRENT_HOSPITAL";
